name: End to End CI/CD workflow for Java application with Maven, sonar and k8s integration

on:
 push:
   branches:
      - main

env:
   KUBECONFIG: ${{ secrets.KUBECONFIG }}
   SONAR_TOKEN: ${{ secrets.SONAR_TKN }}

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: checkout code 
      uses: actions/checkout@v2

    - name: java jdk setup 
      uses: actions/setup-java@v1
      with:
        java-version: 12 

    - name: maven target 
      run: maven clean install
  
    - name: perform analysis on soanr qube 
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        sonarcloud.organization: <name of your org>
        sonarcloud.projectKey: <key>
        sonarcloud.projectName: <name>
        sonarcloud.token: ${{ env.SONAR_TKN }}
        sonarcloud.scannerVersion: "4.2.0.1873"

  deploy:
     needs: build 
     runs-on: ubuntu-latest

     steps:
     - name: checkout code 
       uses: actions/checkout@v2
 
     - name: Deploy to k8s
       uses: tefanzweifel/k8s-action@v2.0.0
       with:
         args: apply -f kubernetes/
       env:
         KUBECONFIG: ${{ env.KUBECONFIG }}

